### ISSUE TITLE
metadata entries are not always an array

### ISSUE THREAD

**Issue by mcollina** [marcopiraccini/sd-swim#5]
```
{ owner: { host: '127.0.0.1', port: 55795 },
  entries: [],
  version: 0 }
{ owner: { host: '127.0.0.1', port: 58972 },
  version: 1,
  entries: MapIterator { [ 'hello', 42 ] } }
    not ok 2 - origin.entries.forEach is not a function
      ---
      stack: >
        data.forEach (gossiply.js:48:24)

        Array.forEach (native)

        SDSwim.Gossiply._swim.on (gossiply.js:46:12)

        Metadata.source.emit
        (/Users/matteo/Repositories/sd-swim/node_modules/propagate/index.js:22:17)

        Metadata._onMeta (/Users/matteo/Repositories/sd-swim/lib/metadata.js:141:12)

        Net.Metadata.net.on (/Users/matteo/Repositories/sd-swim/lib/metadata.js:45:47)

        Socket.socket.on (/Users/matteo/Repositories/sd-swim/lib/net.js:57:19)
 ```

**Comment by marcopiraccini** [comment]
The code doesn't make hypothesis on metadata structure, but the problem is the current protobuf definition, which is a `repeated`: (https://github.com/marcopiraccini/sd-swim/blob/master/lib/proto/sd-swim.proto#L60): 

```
message Entry {
  required string key = 1;
  required string value = 2;
}

message Metadata {
  required Node owner = 1;
  repeated Entry entries = 2;
  required int32 version = 3; // Only the owner can update the version
}
```

So not sure what can be done here. If we "convert" the metadata entries to array when sending, the receiveing nodes will not be able to convert it back to somthing different from array.

**Comment by mcollina** [comment]
The whole API for those is very unclear from the README.
I think we might want the value to be a `Buffer`, so that it's totally generic. Maybe an API like `setMetadata(key, value)` is easier to understand.

**Comment by marcopiraccini** [comment]
Here a PR that uses a Buffer as metadata values with (hopefully :)) more clearer APIs: https://github.com/marcopiraccini/sd-swim/pull/9
